{% set name = "mbdata" %}
{% set version = "27.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mbdata-{{ version }}.tar.gz
  sha256: 83c17e6670fe73ecf3bb1bfcb5eecbf9ad8bb9e3bc4ea6daa19cdbc2b6f1aab5

build:
  noarch: python
  entry_points:
    - mbslave=mbdata.replication:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - psycopg2
    - six >=1.16.0,<2.0.0
    - lxml
    - sqlalchemy

test:
  imports:
    - mbdata
  commands:
    - pip check
    - mbslave --help
  requires:
    - pip

about:
  home: https://github.com/acoustid/mbdata
  summary: MusicBrainz Database Tools
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/acoustid/mbdata

extra:
  recipe-maintainers:
    - HeavyTony2
