{% set name = "mbdata" %}
{% set version = "27.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mbdata-{{ version }}.tar.gz
  url: https://github.com/acoustid/mbdata/archive/v{{ version }}.tar.gz
  sha256: dc131ee528a6d918b309e01eb1d8a608096a10086eafb8c55e9b6cec9691f8f8
  
build:
  noarch: python
  entry_points:
    - mbslave=mbdata.replication:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
  run:
    - python >=3.7,<4.0
    - psycopg2
    - six >=1.16.0,<2.0.0
    - lxml
    - sqlalchemy

test:
  imports:
    - mbdata
  commands:
    - pip check
    - mbslave --help
  requires:
    - pip

about:
  home: https://github.com/acoustid/mbdata
  summary: MusicBrainz Database Tools
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/acoustid/mbdata

extra:
  recipe-maintainers:
    - HeavyTony2
